matrix:
  include:
    - language: java
      jdk: openjdk11
      before_script:
        - cd dit-calendar-bot
        - gradle assemble
      script:
        - gradle build

    - language: elm
      elm:
        - latest-0.19.1
      elm-test: 0.19.1-revision2
      elm-format: 0.8.2
      before_script:
        - cd dit-calendar-ui
      script:
        - elm make src/Main.elm --output src/Main.js
        - elm-test

    - env: HAPPYVER=1.19.5
      language: haskell
      ghc:
        - "8.6.1"
      before_install:
        - cd dit-calendar-server
        - cabal install happy-$HAPPYVER
      script:
        - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
        - cabal build
        - cabal test
        - cabal check
