# .travis.yml
language: haskell
ghc: 8.0

matrix:
  fast_finish: true
  include:
    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.1
      compiler: ": #GHC 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}
