language: c

cache:
  directories:
  - $HOME/.stack
  - .stack-work

# The different configurations we want to test.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
matrix:
  include:
  - env: ARGS="--stack-yaml stack-8.0.yaml"
    compiler: ": #stack 8.0.1"
    addons: { apt: { packages: [libgmp-dev] } }

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc $ARGS build happy
- stack --no-terminal $ARGS test --bench --only-dependencies

script:
- stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps --ghc-options=-Werror

before_cache:
- stack --no-terminal $ARGS clean test-fixture
