apiVersion: apps/v1
kind: Deployment
metadata:
  name: dit-calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dit-calendar
  template:
    metadata:
      labels:
        app: dit-calendar
    spec:
      containers:
      - image: ditcalendar/dit-calendar:latest
        name: dit-calendar
        volumeMounts:
          - name: dit-calendar-volume
            mountPath: /app/state
      volumes:
        - name: dit-calendar-volume
          persistentVolumeClaim:
            claimName: dit-calendar-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dit-calendar-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: dit-calendar
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "dit-calendar"
    port: 8080
  selector:
    app: dit-calendar
