kind: Deployment
apiVersion: apps/v1
metadata:
  name: dit-calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dit-calendar-server
  template:
    metadata:
      labels:
        app: dit-calendar-server
    spec:
      containers:
      - image: ditcalendar/dit-calendar-server:latest
        name: dit-calendar-server
        volumeMounts:
          - name: dit-calendar-volume
            mountPath: /app/state
        resources:
          requests:
            memory: "2Gi"
      volumes:
        - name: dit-calendar-volume
          persistentVolumeClaim:
            claimName: dit-calendar-storage

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dit-calendar-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---

kind: Service
apiVersion: v1
metadata:
  name: dit-calendar-server
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "dit-calendar-server"
    port: 8080
  selector:
    app: dit-calendar-server
