kind: Deployment
apiVersion: apps/v1
metadata:
  name: dit-calendar-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dit-calendar-server
      tier: backend
  template:
    metadata:
      labels:
        app: dit-calendar-server
        tier: backend
    spec:
      volumes:
        - name: dit-calendar-volume
          persistentVolumeClaim:
            claimName: dit-calendar-storage
      containers:
      - image: ditcalendar/dit-calendar-server:latest
        name: dit-calendar-server
        resources:
          requests:
            cpu:    "1"
            memory: "2Gi"
          limits:
            cpu:    "2"
            memory: "4Gi"
        volumeMounts:
          - name: dit-calendar-volume
            mountPath: /app/state

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dit-calendar-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---

kind: Service
apiVersion: v1
metadata:
  name: dit-calendar
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "dit-calendar"
    port: 8080
  selector:
    app: dit-calendar-server
    tier: backend
